# Configuración para el caché de candidatos
quarkus.cache.caffeine."product-candidate-cache".initial-capacity=100

# 1. Tamaño máximo para no agotar el Heap (-Xmx)
quarkus.cache.caffeine."product-candidate-cache".maximum-size=1000

# 2. Tiempo de vida (10 minutos suele ser el estándar para productos)
quarkus.cache.caffeine."product-candidate-cache".expire-after-write=10m

#(Opcional) Registro de métricas para monitoreo
#quarkus.cache.enabled=true




# Configuración para el caché
quarkus.cache.caffeine."product-prices-cache".initial-capacity=100

# 1. Tamaño máximo para no agotar el Heap (-Xmx)
quarkus.cache.caffeine."product-prices-cache".maximum-size=1000

# 2. Tiempo de vida (10 minutos)
quarkus.cache.caffeine."product-prices-cache".expire-after-write=10m

