# Configuración para el caché de candidatos
quarkus.cache.caffeine."product-candidate-cache".initial-capacity=100

# 1. Tamaño máximo para no agotar el Heap (-Xmx)
quarkus.cache.caffeine."product-candidate-cache".maximum-size=1000

# 2. Tiempo de vida (10 minutos suele ser el estándar para productos)
quarkus.cache.caffeine."product-candidate-cache".expire-after-write=10m

quarkus.cache.caffeine."product-candidate-cache".soft-values=true

#(Opcional) Registro de métricas para monitoreo
#quarkus.cache.enabled=true



# Configuración del Caché Product Prices
quarkus.cache.caffeine."product-prices-cache".initial-capacity=100
quarkus.cache.caffeine."product-prices-cache".maximum-size=1000
quarkus.cache.caffeine."product-prices-cache".expire-after-write=10m
quarkus.cache.caffeine."product-prices-cache".soft-values=true


# Configuración del Caché user zone
quarkus.cache.caffeine."user-zone-cache".initial-capacity=1000
quarkus.cache.caffeine."user-zone-cache".maximum-size=5000
quarkus.cache.caffeine."user-zone-cache".expire-after-write=1H
quarkus.cache.caffeine."user-zone-cache".soft-values=true

# Configuración del Caché Restaurant Batch
quarkus.cache.caffeine."restaurants-batch-cache".initial-capacity=100
quarkus.cache.caffeine."restaurants-batch-cache".maximum-size=5000
quarkus.cache.caffeine."restaurants-batch-cache".expire-after-write=2m
quarkus.cache.caffeine."restaurants-batch-cache".soft-values=true
