package org.delicias.common.dto.order;

public enum OrderStatus {
    ORDERED,
    ACCEPTED,
    COOKING,
    READY_FOR_DELIVERY,
    DELIVERY_ASSIGNED_ORDER,
    DELIVERY_ROAD_TO_STORE,
    DELIVERY_ROAD_TO_DESTINATION,
    DELIVERED,
    CANCELLED,
    REJECTED,
    READY_FOR_PICKUP
}
